version: '3'
services:
  tftp:
    image: jumanjiman/tftp-hpa:latest
    volumes:
      - ./tftp/config/pxelinux.cfg:/tftpboot/config/pxelinux.cfg:ro
      - ./tftp/rules/mapfile:/tftpboot/rules/default:ro
    environment:
      - TFTP_USERNAME="tftp"
      - TFTP_DIRECTORY="\tftpboot"
      - TFTP_ADDRESS="0.0.0.0:69"
      - TFTP_OPTIONS="-l -c -s"
    ports:
      - "69:69/udp"

  dhcp:
    image: networkboot/dhcpd:latest
    command: ens3f3
#    command: eth0
    volumes:
      - ./dhcp:/data
#    cap_add:
#      - NET_BIND_SERVICE
#      - NET_ADMIN
#      - SYS_ADMIN
#    ports:
#      - "67:67/udp"
    network_mode: "host"
