version: '3'
services:
  tftp:
    image: jumanjiman/tftp-hpa:latest
    volumes:
      - ./tftp/config:/tftpboot
      - ./tftp/rules:/tftpboot/rules/default
    ports:
      - "69:69/udp"

  dhcp:
    image: networkboot/dhcpd:latest
    command: ens3f3
#    command: eth0
    volumes:
      - ./dhcp:/data
#    cap_add:
#      - NET_BIND_SERVICE
#      - NET_ADMIN
#      - SYS_ADMIN
#    ports:
#      - "67:67/udp"
    network_mode: "host"
